server:
  port: 8002

spring:
  application:
    name: mes-backend
  datasource:
    url: jdbc:postgresql://localhost:25432/mes_db
    username: mes_user
    password: mes_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.hibernate.SQL: debug
